baseURL = "https://sigitwahyudi.netlify.app/"
languageCode = "en-us"
theme = "second"
title = "Sigit Wahyudi"

[permalinks]
  blog = ":slug"
  catatan = ":slug"


[Params]
Description = "Sigit Wahyudi eswe TIK UBT Borneo Web Blog. bikin web dan aplikasi. programmer blogger Tarakan Kaltara"
twitter = "https://www.twitter.com/eswetwit"

[menu]

	[[menu.main]]
	name = "Beranda"
	url = "/"

	[[menu.main]]
	name = "Blog"
	url = "/blog"
	

	[[menu.main]]
	name = "Catatan"
	url = "/catatan"


	[[menu.main]]
	name = "Hubungi"
	url = "/kontak"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
