baseURL = "https://sigitwahyudi.netlify.app/"
languageCode = "en-us"
title = "Kesempatan Kedua new"
theme = "second"
[Params]
twitter = "https://www.twitter.com/eswetwit"
Description = "Sigit Wahyudi Web"